# Generated by Django 4.2.19 on 2025-02-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="healthdata",
            name="username",
            field=models.CharField(default="UnknownUser", max_length=150),
        ),
        migrations.AlterField(
            model_name="healthdata",
            name="bad_habits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthdata",
            name="health_conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthdata",
            name="medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
