# Generated by Django 4.2.19 on 2025-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_healthdata_user_alter_healthdata_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthdata", name="timestamp", field=models.DateTimeField(),
        ),
    ]
