# Generated by Django 4.2.19 on 2025-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_id_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthdata", name="timestamp", field=models.CharField(),
        ),
    ]
