# Generated by Django 4.2.19 on 2025-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_healthdata_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthdata", name="timestamp", field=models.DateTimeField(),
        ),
    ]
